//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementSystemApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Post { get; set; }
        public string Qualification { get; set; }
        public string Skills { get; set; }
        public string Hiring { get; set; }
        public string Description { get; set; }

        internal static void Update(Models.InformationOfEmployee emp)
        {
            throw new NotImplementedException();
        }
    }
}
