//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementSystemApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeManagement
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string ProjectDetails { get; set; }
        public string Trainings { get; set; }
        public string Apprasel { get; set; }
    
        public virtual EmployeeManagement EmployeeManagement1 { get; set; }
        public virtual EmployeeManagement EmployeeManagement2 { get; set; }
    }
}
