//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementSystemApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public EmployeeDetail()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Payrolls = new HashSet<Payroll>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Post { get; set; }
        public string Qualification { get; set; }
        public string Skills { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<double> Salary { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<Payroll> Payrolls { get; set; }
    }
}
