//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementSystemApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Salary { get; set; }
        public string ExpenseClaims { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    }
}
